language: ruby

rvm: 2.1.5

sudo: false

cache: bundler

before_install:
  - cp config/travis.example.yml config/travis.yml

bundler_args: --without development --deployment

notifications:
  slack:
    secure: "tLXxDzcf12es302Fjm+Gl/2/+G2FvMBOIeWYUDx1fvvnNm5DtILkDI9DVm9l0NmW0UlWzEO0NQLkspQtdBP9alehtvuaMO9VUnYwdTdcRYcOKYdDvifFzNrswhZ1nzbevI3AObiJwWWn3Guvi8jBmJxrdw0GFVUpnnbasGncryQAIU1yMQMKoUE5PvFafaVsXW/qIEEnWvWbqtos9Heuw8wYjEz2DIdTDjhIEErDnWd4wtTx+RazLT6fOakXd1bJNxye/VJ48W6PsLYveN2kXhuYrkjCr+5dkNjC1dPw2/GlgMFvfgmAG9xpOv3xeZ9Ie+xZ/F/nAS6pUm/SLuKiLbPN3baP8GQiSCURiuzzI7gHnsh6hq4iBQCb2YXeIrkyue2dRrlNi8PUQlqK9niOt60KxPFJQk6Z1Xo8mAYmxLuJveCH1Eo6gVllub+XNLywFRLdY1sUrBHtmZruIUkB6c5dozlBWJbTSDwoxb0reESehAwmLSRtbZUpapOlhs6ZpHFovSZHuL5/B9wJspozk+L4ZduQWvmwwAw93uREt8aL1gddubZP6WBVC0z6dM2QPyDJ66ElBXNRQIlwouTpTPcOPVdX7knl5SE+BVRZz5wg9JdIHfKhNpnAUooDdSoGte78t/H1esO8tUApKHkAEmiTNbP480byEaTaydb53qE="
