test:
  redis:
    url: redis://tok:en@url.com:12345
  jwt:
    issuer: test_jwt_issuer
    secret: superduper
    algorithm: HS256
  backend:
    s3:
      id: foo
      secret: bar
      region: us-east-1
      bucket: mybucket
